

services:
  
  db:
    container_name: psql_db
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    ports:
      - "5430:5432"

    networks:
      - bot_network

    environment:
      POSTGRES_PASSWORD: password


  redis:
    container_name: redis_container 
    image: redis
    ports:
      - 7979:6379
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
   
volumes:
  postgres_data:
     driver: local