

services:
  app:
    container_name: botapp
    build:
      context: .
    ports:
      - "8085:8085"
    depends_on:
      - db
      - redis
    networks:
      - bot_network
    environment:
      - DB_URL=postgres://postgres:password@db:5432/botdb?sslmode=disable
      - DB_HOST=db
      - REDIS_URL=rd:6379 # Assuming redis is used, let's inject it if necessary

  db:
    container_name: botdb
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    
    ports:
      - "5430:5432"

    networks:
      - bot_network

    environment:
      POSTGRES_PASSWORD: password


  redis:
    container_name: rd
    image: redis
    ports:
      - 7979:6379
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge
   
volumes:
  postgres_data:
     driver: local