
db:
  dbname: botdb
  host: localhost 
  url: postgres://postgres:password@localhost:5430/botdb?sslmode=disable
  
migiration:
  path: internal/constant/query/schemas

tg:
  token: TOKEN_FROM_BOTFATHERS
  bot_username: gabaaBot

lakipay:
  api_key: your_lakipay_api_key
  base_url: https://api.lakipay.co
  callback_url: https://your-api-host/api/v1/webhook/lakipay
  public_key: |
    -----BEGIN PUBLIC KEY-----
    ...
    -----END PUBLIC KEY-----
